/*
 * AUTOGENERATED FROM workflow_1_daily_content.ts — DO NOT EDIT BY HAND
 * Source: ../maroa-ai-marketing-automator/src/lib/prompts/workflow_1_daily_content.ts
 * Regenerate: node scripts/sync_foundation.mjs
 * --------------------------------------------------------------------------- 
 * Source SHA-256 (first 12): e174e41743de
 */
'use strict';

/**
 * Workflow #1 — Daily Content Engine
 * ============================================================================
 * Senior content strategist prompt module. Produces the daily plan, strategic
 * concepts, and platform-native generation briefs per MAROA_15_WORKFLOWS_V2
 * section "WORKFLOW #1 — DAILY CONTENT ENGINE".
 *
 * The Railway worker calls this module through a shared bundle; the generated
 * system+user prompts are sent to Claude Opus (strategic phase) and Sonnet
 * (generation phase). Quality gates and learning loop live in the backend;
 * this module is the strategic mind only.
 * ============================================================================
 */

const { buildSystemPrompt } = require('./foundation.js');

// ---------------------------------------------------------------------------
// PHASE 2 — Strategic Decision Prompt (Claude Opus, ~1500 tokens out)
// ---------------------------------------------------------------------------

function buildStrategicDecisionPrompt(ctx, bundle) {
  const addendum = `
WORKFLOW #1 — DAILY CONTENT ENGINE, STRATEGIC DECISION PHASE

You are acting as the Head of Content Strategy at a senior agency, planning
today's content for ${ctx.businessName}.

Do NOT jump to tactics. Answer these strategic questions IN ORDER, showing
your reasoning explicitly:

  1. WHERE is this brand in its maturity journey?
     (Early / Growth / Mature / Incumbent — this dictates content balance.)
  2. WHAT narrative arc are we in this quarter?
     (Launch / Scale / Reposition / Defend / Expand.)
  3. WHAT is the cultural opportunity TODAY?
     - Trending topic we can authentically join?
     - Seasonal moment to claim?
     - Competitor weakness to exploit?
     - White space to claim?
     If none are strong, say so and design from first principles.
  4. WHICH funnel stages need attention?
     Look at pipeline state + 30-day mix. Are we TOFU-starved? BOFU-ready?
  5. WHICH content pillars are under-served?
     Compare pillarMixStatus target vs actual30d. Rebalance explicitly.
  6. WHICH emotions should today's content evoke?
     Choose 1–2 from: curiosity, aspiration, belonging, relief, pride, FOMO,
     nostalgia, hope, vindication. Justify WHY these and not others.

Then design 1–3 content concepts for today. Each concept MUST include:

  - platform: one of instagram_reel, instagram_story, instagram_feed, tiktok,
              linkedin, facebook, twitter, youtube_shorts, gbp_post
  - format:   specific format within platform (e.g. "9:16 Reel 7–15s", "PDF carousel 8 slides")
  - pillar:   which content pillar it serves
  - funnelStage: tofu | mofu | bofu | retention
  - emotion:  the primary emotional beat
  - coreIdea: one sentence — the concept in plain English
  - hook:     first 3 seconds (or first line for text posts). Use one of the
              validated hook patterns: Pattern Interrupt, Curiosity Gap,
              Value Promise, Contrarian, Storytelling. NAME which pattern.
  - storyArc: if video/carousel, the beat-by-beat arc
  - cta:      specific action you want the audience to take
  - framework: which psychology lever is load-bearing (Cialdini principle,
               StoryBrand role, Kahneman bias, JTBD job). One or two max —
               NOT a laundry list. Say WHY it's load-bearing here.
  - whyThisWhyNow: 2 sentences connecting this concept to the cultural,
                   competitive, and pillar-mix state above
  - predictedEngagementRange: [low, high] as decimal (e.g. [0.03, 0.06] = 3–6%)
  - riskLevel: low | medium | high — high = experimental, off-pillar, trend-chasing
  - costEstimate: USD, realistic ($0.15 image / $0.35 carousel / $0.65 reel /
                  $0.45 tiktok / $0.25 linkedin article)

OUTPUT FORMAT: strict JSON matching this TypeScript type:

  {
    "analysis": {
      "brandMaturity": "early" | "growth" | "mature" | "incumbent",
      "narrativeArc": "launch" | "scale" | "reposition" | "defend" | "expand",
      "culturalOpportunity": string,  // 2–3 sentences naming the opportunity (or "none — designing from first principles")
      "funnelStagesNeedingAttention": ("tofu" | "mofu" | "bofu" | "retention")[],
      "underservedPillars": string[],
      "targetEmotions": string[],
      "reasoning": string  // 4–6 sentences, senior-strategist voice — this is shown to the client in the approval UI
    },
    "concepts": [ /* 1–3 concepts as specified above */ ]
  }

HARD REQUIREMENTS
- Concepts MUST respect the 80/20 value/ask ratio (max 1 of 3 may be promotional).
- Must pass the LTV:CAC sanity check (no campaigns violating Principle 3).
- Must respect crisis/holiday sensitivity (no food promo during Ramadan daylight
  in Muslim-majority markets; no non-essential content during major tragedies).
- Must respect topic cooldown: no topic repeated within 7 days unless trending
  with <24h half-life (then flag explicitly).
- Must respect platform-optimal daily limits (max 3/platform/day, min 4h spacing).
- NEVER fabricate metrics. If predicting, base on this account's historical
  performance and industry benchmarks cited in INDUSTRY_PLAYBOOKS.
- If no strong concept is possible today, return { "concepts": [] } with
  reasoning — skipping a day is better than posting weak content.
`.trim();

  const user = `
DAILY CONTEXT BUNDLE (${bundle.cultural.todayLocalDate})

BRAND MEMORY
Voice: ${bundle.brandMemory.voiceProfile}
Winning patterns (top ${bundle.brandMemory.historicalWinners.length}):
${bundle.brandMemory.historicalWinners.map(w => `  • [${w.format}] "${w.hook}" — ${w.trait} — +${Math.round(w.engagementLift * 100)}% vs baseline`).join('\n')}

Anti-patterns to avoid:
${bundle.brandMemory.antiPatterns.map(a => `  • ${a.reason}: ${a.example}`).join('\n')}

Pillar mix (target vs actual 30d):
${bundle.brandMemory.pillarMixStatus.map(p => `  • ${p.pillar}: ${p.target}% target / ${p.actual30d}% actual ${p.actual30d < p.target ? '⬇ UNDER' : p.actual30d > p.target ? '⬆ OVER' : '= on target'}`).join('\n')}

PERFORMANCE (last 30d)
${bundle.performance.last30d.map(p => `  • ${p.platform}: ${p.posts} posts, ${(p.avgEngagement * 100).toFixed(1)}% avg eng (${p.vsBenchmark > 0 ? '+' : ''}${(p.vsBenchmark * 100).toFixed(0)}% vs industry benchmark)`).join('\n')}
Growth: follower Δ30d = ${bundle.performance.growthTrajectory.followerDelta30d > 0 ? '+' : ''}${bundle.performance.growthTrajectory.followerDelta30d}; engagement trend = ${bundle.performance.growthTrajectory.engagementTrend}
Saturation/fatigue score: ${bundle.performance.saturationFatigueScore}/100

CULTURAL
Upcoming holidays:
${bundle.cultural.upcomingHolidays.map(h => `  • ${h.date} — ${h.name} (${h.type})`).join('\n') || '  (none)'}
${bundle.cultural.seasonalMoment ? `Seasonal moment: ${bundle.cultural.seasonalMoment}\n` : ''}
Trending topics:
${bundle.cultural.trendingTopics.map(t => `  • [${t.platform}] ${t.topic} — velocity=${t.velocity}, relevance=${t.relevance}/10`).join('\n') || '  (none relevant)'}
News cycle:
${bundle.cultural.newsCycle.map(n => `  • ${n.headline} (${n.source}, relevance ${n.relevance}/10)`).join('\n') || '  (none relevant)'}

COMPETITIVE (last 24h)
${bundle.competitive.last24h.map(c => `  • ${c.competitor} [${c.platform}] "${c.topic}" — ${c.format}, est. engagement ${(c.estimatedEngagement * 100).toFixed(1)}%`).join('\n') || '  (quiet)'}
Gap opportunities: ${bundle.competitive.gapOpportunities.join(' | ') || '(none)'}
White space:       ${bundle.competitive.whiteSpace.join(' | ') || '(none)'}

AUDIENCE (last 48h)
${bundle.audience.topComments48h.map(c => `  • [${c.platform}] ${c.topic} — sentiment=${c.sentiment.toFixed(2)}, volume=${c.volume}`).join('\n') || '  (quiet)'}
Demographic shifts: ${bundle.audience.demographicShifts ?? 'none detected'}
Drop-off signals: ${bundle.audience.dropOffSignals.join('; ') || 'none'}

BUSINESS
Active campaigns:
${bundle.business.activeCampaigns.map(c => `  • ${c.name} (${c.funnelStage}) ends ${c.endsAt}`).join('\n') || '  (none)'}
${bundle.business.inventoryOrPromoCalendar ? `Inventory/promo: ${bundle.business.inventoryOrPromoCalendar}\n` : ''}
${bundle.business.salesPriorities?.length ? `Sales priorities: ${bundle.business.salesPriorities.join('; ')}\n` : ''}
${bundle.business.launchPipeline?.length ? `Launch pipeline:\n${bundle.business.launchPipeline.map(l => `  • ${l.name} — T-${l.daysUntil}d`).join('\n')}\n` : ''}
`.trim();

  return {
    system: buildSystemPrompt(ctx, addendum),
    user,
  };
}

// ---------------------------------------------------------------------------
// PHASE 3 — Platform-native generation brief (per concept, per platform)
// ---------------------------------------------------------------------------

const PLATFORM_GENERATION_SPECS = {
  instagram_reel: `
INSTAGRAM REEL — the highest-ROI format 2024–2026
  Aspect 9:16. Duration 7–15s sweet spot. Res 1080x1920 min, 1440x2560 preferred.
  Safe zones: top 250px, bottom 570px.
  Hook architecture (first 3s = 80% of performance). Use one of: Pattern Interrupt,
    Curiosity Gap, Value Promise, Contrarian, Storytelling. Name which.
  Caption formula (Later, 1M-post study): hook restated / blank / story 4 lines /
    blank / soft CTA / blank / 3–5 hashtags (NOT 30 — IG 2023 algo).
  Hashtag mix: 1 branded + 1–2 niche + 1–2 broad (only if genuinely relevant).
  Captions burned-in (85% watch on mute — Wistia). Face in thumbnail = +34% tap rate.
  Trending audio: 2.1x reach first 72h, but only if relevant.
`.trim(),

  instagram_story: `
INSTAGRAM STORY — highest completion rate, daily presence layer
  Aspect 9:16. 5–15s per frame. 3–7 frames per sequence (more = drop-off).
  Archetypes: BTS > Polls/Questions (60% interaction) > Product demo (35% tap-through)
    > Team spotlight (42% completion) > UGC repost > Teaser.
  Interactive elements: poll, question, quiz, slider, countdown, link sticker.
  Use strategically — not randomly.
`.trim(),

  instagram_feed: `
INSTAGRAM FEED — permanent home, discoverability, portfolio
  Square 1080x1080 or portrait 1080x1350 (portrait = +30% reach).
  Carousel format: 2.3x engagement of single image. 8–10 slides optimal.
  Caption: hook in first 125 chars (above "more"), then story, soft CTA, 3–5 hashtags.
`.trim(),

  tiktok: `
TIKTOK — algorithm rewards watch-time % and rewatches above all
  Duration 15–30s for highest completion. 30–60s only if retention >50%.
  NEVER: watermarked cross-posts (penalized), external links in content, sales-heavy
    hooks, non-library music (copyright flag).
  Native iPhone-shot aesthetic > polished. Creator voice > stock.
  Hashtags: 3–5, mix broad + niche + 1–2 content category (#learn #howto).
  Formats: POV, duet/stitch, trending sound → niche, day-in-life, storytimes,
    product reveals w/ build-up, before/after.
`.trim(),

  linkedin: `
LINKEDIN — organic reach 5–8% of followers, very different algorithm
  Format hierarchy by reach (van der Blom 2024): PDF carousel 2.3x > text+image 1.7x
    > native video 1.5x > polls 1.4x > text 1.0 > links 0.5x.
  Length sweet spot: 1200–1500 chars. Hook in line 1 (above the fold cutoff).
  Links in FIRST COMMENT, never in body (50% reach penalty).
  B2B content mix: 40% thought leadership / 20% education / 20% story / 10% community / 10% promo.
  Frequency: 2–5 posts/week (beyond 5 = diminishing returns).
`.trim(),

  facebook: `
FACEBOOK — organic reach 1.52%, valuable for community groups, older demo, events
  Native video > external links. Longer-form text (FB rewards dwell time).
  Community groups > page posts. Live video = highest organic reach on platform.
`.trim(),

  twitter: `
TWITTER/X — thought leadership, real-time commentary
  Algorithm favors: long-form posts, reply engagement, X Premium boost.
  Threads still work — must deliver value in first tweet. 3–5 posts/day for B2B thought leaders.
  Quote-tweet commentary on industry news within 24h = authority signal.
`.trim(),

  youtube_shorts: `
YOUTUBE SHORTS — duration <60s, 9:16, growing CPM advantage vs Reels
  Hook in first 2s. Strong mid-video retention pattern (expected drop-off at 6s, 15s, 30s).
  Title + thumbnail = 70% of CTR. Title pattern: curiosity gap or value promise.
`.trim(),

  gbp_post: `
GOOGLE BUSINESS PROFILE POST — local SEO + conversion layer
  160 char summary, 1500 char body, CTA button (book / order / learn more / call).
  Types: update, event, offer, product. Offer posts get highest CTR.
  Post DAILY for local services — inactivity hurts ranking.
  Images: 1200x900, bright, no text overlay (Google strips it).
`.trim(),
};

function buildPlatformGenerationPrompt(ctx, concept) {
  const addendum = `
WORKFLOW #1 — DAILY CONTENT ENGINE, PLATFORM GENERATION PHASE

You are now the copywriter + creative director for ${ctx.businessName}, writing
a single piece of content for ${concept.platform}. The strategist has already
made the strategic call — your job is execution at senior-agency quality.

PLATFORM SPEC (memorize this)
${PLATFORM_GENERATION_SPECS[concept.platform]}

QUALITY GATES (your output must clear all of these — the backend enforces)
  Brand voice match:        20 pts   — LLM will compare your draft to brand profile
  Hook strength:            20 pts   — predicted stop-scroll probability
  Visual brief quality:     20 pts   — resolution, composition, brand colors specified
  Pattern freshness:        15 pts   — no tired templates
  Prediction confidence:    15 pts   — your own confidence in performance
  Compliance:               10 pts   — no banned words / legal issues / copyrights
Total must be ≥80 to pass approval, ≥95 for auto-post.

OUTPUT FORMAT: strict JSON

  {
    "caption": string,             // the ready-to-post copy
    "hook": string,                // the hook verbatim
    "hookPattern": "pattern_interrupt" | "curiosity_gap" | "value_promise" | "contrarian" | "storytelling",
    "hashtags": string[],          // 3–5 items, brand|niche|broad mix
    "cta": string,                 // explicit action
    "visualBrief": {
      "format": string,            // e.g. "9:16 Reel, 10s"
      "shots": string[],           // ordered shot list for video/carousel
      "style": string,             // cinematic reference, mood, lighting
      "brandAssets": string[],     // logos, colors, fonts to apply
      "thumbnailGuidance": string  // face? text overlay? emotion?
    },
    "accessibilityAltText": string,
    "burnedInCaptions": string | null, // only for video
    "postingTime": {
      "localTime": string,         // HH:MM in business timezone
      "rationale": string          // why this time
    },
    "frameworkJustification": string, // 1–2 sentences naming the psychology lever
    "predictedQualityScore": number,  // 0–100, your self-assessment
    "confidence": number              // 0–1, how confident you are in the prediction
  }

HARD REQUIREMENTS
- Match the brand voice exactly. If banned words exist, do not use them.
- Hook MUST match the declared hookPattern.
- Caption MUST use the platform's tested caption formula (see spec above).
- NO stock phrases ("engage your audience", "take your brand to the next level").
- Psychology lever must be LOAD-BEARING, not decoration.
- For visual brief: be specific enough that a Higgsfield/Segmind operator could
  execute without further input.
`.trim();

  const user = `
CONCEPT TO EXECUTE

  Platform:        ${concept.platform}
  Format:          ${concept.format}
  Content pillar:  ${concept.pillar}
  Funnel stage:    ${concept.funnelStage}
  Emotion:         ${concept.emotion}
  Core idea:       ${concept.coreIdea}
  Strategist's hook direction: ${concept.hook}
  Story arc (if any): ${concept.storyArc ?? 'n/a'}
  Desired CTA:     ${concept.cta}
  Framework lever: ${concept.framework}
  Why this, why now: ${concept.whyThisWhyNow}
  Predicted engagement: ${(concept.predictedEngagementRange[0] * 100).toFixed(1)}–${(concept.predictedEngagementRange[1] * 100).toFixed(1)}%
  Risk level:      ${concept.riskLevel}
  Cost budget:     $${concept.costEstimate.toFixed(2)}

Execute.
`.trim();

  return {
    system: buildSystemPrompt(ctx, addendum),
    user,
  };
}

// ---------------------------------------------------------------------------
// Autonomy modes — thresholds the backend enforces
// ---------------------------------------------------------------------------

const AUTONOMY_MODES = {
  full_autopilot: {
    label: 'Full Autopilot',
    description:
      'AI publishes when quality ≥95. Best for mature brands with established voice. +23% engagement in beta (catches trend waves, less second-guessing).',
    autoPublishThreshold: 95,
    requireApprovalBelow: 95,
  },
  hybrid: {
    label: 'Hybrid (recommended default)',
    description:
      'You approve within 4 business hours; after that, quality ≥90 auto-publishes. Quality ≥95 auto-publishes immediately. Captures 78% of trend-wave peak engagement.',
    autoPublishThreshold: 95,
    fallbackAutoPublishAfterHours: 4,
    fallbackThreshold: 90,
  },
  approve_everything: {
    label: 'Approve Everything',
    description:
      'All posts require explicit approval. Recommended for regulated industries (legal, medical, finance) and early-stage accounts still defining voice.',
    autoPublishThreshold: null,
  },
};

// ---------------------------------------------------------------------------
// Guardrails the backend enforces server-side (documented here for clarity)
// ---------------------------------------------------------------------------

const WF1_GUARDRAILS = {
  volume: {
    maxPostsPerPlatformPerDay: 3,
    minMinutesBetweenSamePlatform: 240,
    storiesMaxPerDay: 10,
  },
  topicCooldownDays: 0,
  trendingExceptionHalfLifeHours: 24,
  crisisAutoPause: {
    triggers: ['natural_disaster', 'public_figure_death', 'major_tragedy', 'contentious_election_day'],
    resumeAfterSentimentNormalizes: true,
    typicalDurationHours: [24, 72],
  },
  holidaySensitivity: {
    ramadanNoFoodPromoInDaylight: true,
    respectDaysOfMourning: true,
    adjustToneForSolemnHolidays: true,
  },
  costPerPostBudgetUsd: {
    image: 0.15,
    carousel: 0.35,
    reel: 0.65,
    tiktok: 0.45,
    linkedinArticle: 0.25,
  },
  monthlyCapUsd: {
    growth: 45, // ~100 pieces
    agency: 180, // ~400 pieces
  },
};


// ── Auto-generated CommonJS exports (sync_foundation.mjs) ──
module.exports.PLATFORM_GENERATION_SPECS = PLATFORM_GENERATION_SPECS;
module.exports.AUTONOMY_MODES = AUTONOMY_MODES;
module.exports.WF1_GUARDRAILS = WF1_GUARDRAILS;
module.exports.buildStrategicDecisionPrompt = buildStrategicDecisionPrompt;
module.exports.buildPlatformGenerationPrompt = buildPlatformGenerationPrompt;
