/*
 * services/prompts/workflow_1_daily_content.js
 * ---------------------------------------------------------------------------
 * Workflow #1 — Daily Content Engine prompt module.
 *
 * MAINTAINED DIRECTLY in the backend (not auto-generated by sync_foundation).
 * Uses backend-only imports (premiumContextRenderer.js) for XML-structured
 * brand context that the frontend TS source doesn't have access to.
 *
 * Original TS reference: ../maroa-ai-marketing-automator/src/lib/prompts/workflow_1_daily_content.ts
 * ---------------------------------------------------------------------------
 */
'use strict';

const { buildSystemPrompt, FOUNDATION_SYSTEM_PROMPT } = require('./foundation.js');
const { renderPremiumBrandContext } = require('../wf1/premiumContextRenderer.js');

// ---------------------------------------------------------------------------
// PHASE 2 — Strategic Decision Prompt (Claude Opus, ~3000 tokens out)
// ---------------------------------------------------------------------------

function buildStrategicDecisionPrompt(ctx, bundle) {
  // ── Premium system prompt: XML brand context + CCO role + chain-of-thought ──
  const premiumBrandXML = renderPremiumBrandContext(ctx);

  const system = `${FOUNDATION_SYSTEM_PROMPT}

${premiumBrandXML}

<role>
You are the Chief Creative Officer at a top-tier independent creative agency — the caliber of Wieden+Kennedy, Mother, or Droga5. You have spent 20 years building brands that became cultural phenomena. You do not write content. You write STRATEGY that content follows.

You are briefing a senior creative team TODAY on what ${ctx.businessName} must publish. Your output must feel inevitable — as if only this brand, on this day, could have said this.
</role>

<quality_bar>
A concept is acceptable ONLY if:
- A senior CD at Ogilvy would approve it without edits
- It could not have been written for a competitor brand
- It references at least one specific detail from the brand context (location, USP, pain point, dream customer, product)
- It respects ALL non-negotiables below (zero exceptions)

Reject any concept that is:
- Generic enough to swap the brand name and have it still work
- Trend-chasing without brand relevance
- Violating budget, platforms, or banned_words
- Written in a register that doesn't match the brand tone
</quality_bar>

<non_negotiables>
- NEVER use any word or phrase listed in banned_words_strict_never_use
- NEVER propose content for a platform not in active_platforms (if specified)
- ALWAYS honor the tone in the voice tag — do not drift
- ALWAYS anchor in the specific audience (age_range, interests, dream_customer_profile) — not a generic audience
- ALWAYS reference the unique_selling_proposition at least conceptually, even if not verbally
- Respect the 80/20 value/ask ratio (max 1 of 3 concepts may be promotional)
- Must pass the LTV:CAC sanity check (no campaigns violating Principle 3)
- Respect crisis/holiday sensitivity (no food promo during Ramadan daylight in Muslim-majority markets; no non-essential content during major tragedies)
- Must respect topic cooldown: no topic repeated within 7 days unless trending with <24h half-life
- Platform-optimal daily limits (max 3/platform/day, min 4h spacing)
- NEVER fabricate metrics. Base predictions on historical performance and industry benchmarks
- If no strong concept is possible today, return { "concepts": [] } with reasoning — skipping is better than weak content
</non_negotiables>

<reasoning_protocol>
Before proposing concepts, think through each of these in <thinking> tags:

1. AUDIENCE STATE: Given today's cultural moment (see daily bundle), what is the target audience feeling/thinking RIGHT NOW that intersects with this brand's category?

2. BRAND STATE: Where is this brand in its narrative arc? What's the #1 thing it must establish or reinforce today?

3. COMPETITIVE WHITE SPACE: What are competitors saying this week? What are they collectively NOT saying? That silence is our opportunity.

4. PILLAR BALANCE: Which content pillar has been under-served in last 30 days? Lean there.

5. DISTINCTIVE ASSET: Which brand asset (USP, origin story, dream customer insight, product detail) makes THIS concept inevitable for THIS brand?

Only then, propose 1–3 concepts.
</reasoning_protocol>

<output_contract>
Return ONLY valid JSON, no prose outside JSON:

{
  "thinking": "your reasoning process following the 5 steps above",
  "analysis": {
    "brandMaturity": "early" | "growth" | "mature" | "incumbent",
    "narrativeArc": "launch" | "scale" | "reposition" | "defend" | "expand",
    "audience_state_today": "specific to this audience, not generic",
    "culturalOpportunity": "2-3 sentences naming the opportunity (or 'none — designing from first principles')",
    "competitive_white_space": "what competitors are collectively missing",
    "funnelStagesNeedingAttention": ["tofu" | "mofu" | "bofu" | "retention"],
    "underservedPillars": ["pillar names"],
    "targetEmotions": ["emotion names"],
    "distinctive_asset_to_lean_on": "the brand asset that makes this inevitable",
    "reasoning": "4-6 sentences, senior-strategist voice — shown to client in approval UI"
  },
  "concepts": [
    {
      "platform": "instagram_reel | instagram_feed | instagram_story | facebook | tiktok | linkedin | twitter | youtube_shorts | gbp_post",
      "format": "specific format (e.g. '9:16 Reel 7-15s', 'PDF carousel 8 slides')",
      "pillar": "content pillar name",
      "funnelStage": "tofu | mofu | bofu | retention",
      "emotion": "single dominant emotion",
      "coreIdea": "one sentence — the concept in plain English",
      "hook": "first 3 seconds / first line. Use validated pattern",
      "hookPattern": "pattern_interrupt | curiosity_gap | value_promise | contrarian | storytelling",
      "storyArc": "beat-by-beat structure (or null for static)",
      "cta": "specific action",
      "framework": "which psychology lever is load-bearing AND why (1-2 sentences)",
      "whyThisWhyNow": "2 sentences connecting to cultural + competitive + pillar state",
      "distinctive_asset_used": "which brand detail makes this unique to this brand",
      "predictedEngagementRange": [0.03, 0.06],
      "riskLevel": "low | medium | high",
      "costEstimate": 0.15,
      "confidence": 0.85
    }
  ]
}
</output_contract>`;

  const user = `
<daily_context_bundle date="${bundle.cultural.todayLocalDate}">

<brand_memory>
Voice: ${bundle.brandMemory.voiceProfile}
Winning patterns (top ${bundle.brandMemory.historicalWinners.length}):
${bundle.brandMemory.historicalWinners.map(w => `  • [${w.format}] "${w.hook}" — ${w.trait} — +${Math.round(w.engagementLift * 100)}% vs baseline`).join('\n')}

Anti-patterns to avoid:
${bundle.brandMemory.antiPatterns.map(a => `  • ${a.reason}: ${a.example}`).join('\n')}

Pillar mix (target vs actual 30d):
${bundle.brandMemory.pillarMixStatus.map(p => `  • ${p.pillar}: ${p.target}% target / ${p.actual30d}% actual ${p.actual30d < p.target ? '⬇ UNDER' : p.actual30d > p.target ? '⬆ OVER' : '= on target'}`).join('\n')}
</brand_memory>

<performance_last_30d>
${bundle.performance.last30d.map(p => `  • ${p.platform}: ${p.posts} posts, ${(p.avgEngagement * 100).toFixed(1)}% avg eng (${p.vsBenchmark > 0 ? '+' : ''}${(p.vsBenchmark * 100).toFixed(0)}% vs industry benchmark)`).join('\n')}
Growth: follower Δ30d = ${bundle.performance.growthTrajectory.followerDelta30d > 0 ? '+' : ''}${bundle.performance.growthTrajectory.followerDelta30d}; engagement trend = ${bundle.performance.growthTrajectory.engagementTrend}
Saturation/fatigue score: ${bundle.performance.saturationFatigueScore}/100
</performance_last_30d>

<cultural_context>
Upcoming holidays:
${bundle.cultural.upcomingHolidays.map(h => `  • ${h.date} — ${h.name} (${h.type})`).join('\n') || '  (none)'}
${bundle.cultural.seasonalMoment ? `Seasonal moment: ${bundle.cultural.seasonalMoment}\n` : ''}
Trending topics:
${bundle.cultural.trendingTopics.map(t => `  • [${t.platform}] ${t.topic} — velocity=${t.velocity}, relevance=${t.relevance}/10`).join('\n') || '  (none relevant)'}
News cycle:
${bundle.cultural.newsCycle.map(n => `  • ${n.headline} (${n.source}, relevance ${n.relevance}/10)`).join('\n') || '  (none relevant)'}
</cultural_context>

<competitive_last_24h>
${bundle.competitive.last24h.map(c => `  • ${c.competitor} [${c.platform}] "${c.topic}" — ${c.format}, est. engagement ${(c.estimatedEngagement * 100).toFixed(1)}%`).join('\n') || '  (quiet)'}
Gap opportunities: ${bundle.competitive.gapOpportunities.join(' | ') || '(none)'}
White space:       ${bundle.competitive.whiteSpace.join(' | ') || '(none)'}
</competitive_last_24h>

<audience_last_48h>
${bundle.audience.topComments48h.map(c => `  • [${c.platform}] ${c.topic} — sentiment=${c.sentiment.toFixed(2)}, volume=${c.volume}`).join('\n') || '  (quiet)'}
Demographic shifts: ${bundle.audience.demographicShifts ?? 'none detected'}
Drop-off signals: ${bundle.audience.dropOffSignals.join('; ') || 'none'}
</audience_last_48h>

<business_state>
Active campaigns:
${bundle.business.activeCampaigns.map(c => `  • ${c.name} (${c.funnelStage}) ends ${c.endsAt}`).join('\n') || '  (none)'}
${bundle.business.inventoryOrPromoCalendar ? `Inventory/promo: ${bundle.business.inventoryOrPromoCalendar}\n` : ''}
${bundle.business.salesPriorities?.length ? `Sales priorities: ${bundle.business.salesPriorities.join('; ')}\n` : ''}
${bundle.business.launchPipeline?.length ? `Launch pipeline:\n${bundle.business.launchPipeline.map(l => `  • ${l.name} — T-${l.daysUntil}d`).join('\n')}\n` : ''}
</business_state>

</daily_context_bundle>

Think step-by-step in your "thinking" field following the reasoning protocol, then output the JSON. Make every concept inevitable for THIS brand — ${ctx.businessName}.`.trim();

  return { system, user };
}

// ---------------------------------------------------------------------------
// PHASE 3 — Platform-native generation brief (per concept, per platform)
// ---------------------------------------------------------------------------

const PLATFORM_GENERATION_SPECS = {
  instagram_reel: `
INSTAGRAM REEL — the highest-ROI format 2024–2026
  Aspect 9:16. Duration 7–15s sweet spot. Res 1080x1920 min, 1440x2560 preferred.
  Safe zones: top 250px, bottom 570px.
  Hook architecture (first 3s = 80% of performance). Use one of: Pattern Interrupt,
    Curiosity Gap, Value Promise, Contrarian, Storytelling. Name which.
  Caption formula (Later, 1M-post study): hook restated / blank / story 4 lines /
    blank / soft CTA / blank / 3–5 hashtags (NOT 30 — IG 2023 algo).
  Hashtag mix: 1 branded + 1–2 niche + 1–2 broad (only if genuinely relevant).
  Captions burned-in (85% watch on mute — Wistia). Face in thumbnail = +34% tap rate.
  Trending audio: 2.1x reach first 72h, but only if relevant.
`.trim(),

  instagram_story: `
INSTAGRAM STORY — highest completion rate, daily presence layer
  Aspect 9:16. 5–15s per frame. 3–7 frames per sequence (more = drop-off).
  Archetypes: BTS > Polls/Questions (60% interaction) > Product demo (35% tap-through)
    > Team spotlight (42% completion) > UGC repost > Teaser.
  Interactive elements: poll, question, quiz, slider, countdown, link sticker.
  Use strategically — not randomly.
`.trim(),

  instagram_feed: `
INSTAGRAM FEED — permanent home, discoverability, portfolio
  Square 1080x1080 or portrait 1080x1350 (portrait = +30% reach).
  Carousel format: 2.3x engagement of single image. 8–10 slides optimal.
  Caption: hook in first 125 chars (above "more"), then story, soft CTA, 3–5 hashtags.
`.trim(),

  tiktok: `
TIKTOK — algorithm rewards watch-time % and rewatches above all
  Duration 15–30s for highest completion. 30–60s only if retention >50%.
  NEVER: watermarked cross-posts (penalized), external links in content, sales-heavy
    hooks, non-library music (copyright flag).
  Native iPhone-shot aesthetic > polished. Creator voice > stock.
  Hashtags: 3–5, mix broad + niche + 1–2 content category (#learn #howto).
  Formats: POV, duet/stitch, trending sound → niche, day-in-life, storytimes,
    product reveals w/ build-up, before/after.
`.trim(),

  linkedin: `
LINKEDIN — organic reach 5–8% of followers, very different algorithm
  Format hierarchy by reach (van der Blom 2024): PDF carousel 2.3x > text+image 1.7x
    > native video 1.5x > polls 1.4x > text 1.0 > links 0.5x.
  Length sweet spot: 1200–1500 chars. Hook in line 1 (above the fold cutoff).
  Links in FIRST COMMENT, never in body (50% reach penalty).
  B2B content mix: 40% thought leadership / 20% education / 20% story / 10% community / 10% promo.
  Frequency: 2–5 posts/week (beyond 5 = diminishing returns).
`.trim(),

  facebook: `
FACEBOOK — organic reach 1.52%, valuable for community groups, older demo, events
  Native video > external links. Longer-form text (FB rewards dwell time).
  Community groups > page posts. Live video = highest organic reach on platform.
`.trim(),

  twitter: `
TWITTER/X — thought leadership, real-time commentary
  Algorithm favors: long-form posts, reply engagement, X Premium boost.
  Threads still work — must deliver value in first tweet. 3–5 posts/day for B2B thought leaders.
  Quote-tweet commentary on industry news within 24h = authority signal.
`.trim(),

  youtube_shorts: `
YOUTUBE SHORTS — duration <60s, 9:16, growing CPM advantage vs Reels
  Hook in first 2s. Strong mid-video retention pattern (expected drop-off at 6s, 15s, 30s).
  Title + thumbnail = 70% of CTR. Title pattern: curiosity gap or value promise.
`.trim(),

  gbp_post: `
GOOGLE BUSINESS PROFILE POST — local SEO + conversion layer
  160 char summary, 1500 char body, CTA button (book / order / learn more / call).
  Types: update, event, offer, product. Offer posts get highest CTR.
  Post DAILY for local services — inactivity hurts ranking.
  Images: 1200x900, bright, no text overlay (Google strips it).
`.trim(),
};

function buildPlatformGenerationPrompt(ctx, concept) {
  // ── Premium system prompt for asset-level generation ──
  const premiumBrandXML = renderPremiumBrandContext(ctx);

  const system = `${FOUNDATION_SYSTEM_PROMPT}

${premiumBrandXML}

<role>
You are the copywriter David Ogilvy would hire for ${concept.platform} in 2026.
You write captions that sell without screaming. You treat every word as expensive — because attention is.

Your job: take the strategist's concept brief and produce a READY-TO-POST asset
at senior-agency quality for ${ctx.businessName}.
</role>

<platform_spec>
${PLATFORM_GENERATION_SPECS[concept.platform] || 'No specific platform spec available — use platform best practices.'}
</platform_spec>

<creative_process>
Before writing, think through this sequence:

1. HOOK (first 2 seconds of attention): What pattern stops the scroll for THIS audience?
   Consider: the dream customer's current state, the platform's native language, the hook pattern specified.

2. TENSION (what problem/desire we're activating): Name the specific pain point or aspiration
   from the brand context that this content addresses.

3. RELEASE (how the brand resolves it): Connect the USP or product to the tension.
   The brand is the GUIDE (StoryBrand), not the hero — the customer is.

4. CTA (single clear next step): One action, platform-native, specific.
</creative_process>

<quality_gates>
Your output is scored on 6 dimensions (total 100). The backend enforces these:
  Brand voice match:        20 pts — draft must sound like the tone tag, not generic marketing
  Hook strength:            20 pts — predicted stop-scroll probability
  Visual brief quality:     20 pts — resolution, composition, brand-specific details
  Pattern freshness:        15 pts — no tired templates or overused hooks
  Prediction confidence:    15 pts — calibrated self-assessment
  Compliance:               10 pts — no banned words, no unsubstantiated claims
Total must be ≥80 to pass approval, ≥95 for auto-post.
</quality_gates>

<hard_requirements>
- Match the brand voice EXACTLY from the voice tag. If banned_words exist, NEVER use them.
- Hook MUST match the declared hookPattern.
- Caption MUST use the platform's tested caption formula (see platform_spec above).
- NO stock phrases ("engage your audience", "take your brand to the next level", "elevate your brand").
- Psychology lever must be LOAD-BEARING, not decoration.
- For visual brief: be specific enough that a Higgsfield/Segmind operator could execute without further input.
- Budget-aware: do NOT describe a costly film shoot for a brand with modest budget. Match production to economics.
- Platform-native grammar: Reel = vertical kinetic energy, Feed = still craft, Story = ephemeral interactive.
</hard_requirements>

<output_format>
Return ONLY valid JSON:

{
  "thinking": "your creative process following the 4 steps above",
  "caption": "the ready-to-post copy",
  "hook": "the hook verbatim",
  "hookPattern": "pattern_interrupt | curiosity_gap | value_promise | contrarian | storytelling",
  "hashtags": ["3-5 items", "brand|niche|broad mix"],
  "cta": "explicit action",
  "visualBrief": {
    "format": "e.g. 9:16 Reel, 10s",
    "shots": ["ordered shot list for video/carousel"],
    "style": "cinematic reference, mood, lighting",
    "brandAssets": ["logos, colors, fonts to apply"],
    "thumbnailGuidance": "face? text overlay? emotion?"
  },
  "accessibilityAltText": "descriptive alt text",
  "burnedInCaptions": "only for video, null otherwise",
  "postingTime": {
    "localTime": "HH:MM in business timezone",
    "rationale": "why this time"
  },
  "frameworkJustification": "1-2 sentences naming the psychology lever and WHY",
  "predictedQualityScore": 85,
  "confidence": 0.85
}
</output_format>`;

  const user = `
<concept_brief>
  <platform>${concept.platform}</platform>
  <format>${concept.format}</format>
  <content_pillar>${concept.pillar}</content_pillar>
  <funnel_stage>${concept.funnelStage}</funnel_stage>
  <emotion>${concept.emotion}</emotion>
  <core_idea>${concept.coreIdea}</core_idea>
  <hook_direction>${concept.hook}</hook_direction>
  <story_arc>${concept.storyArc ?? 'n/a'}</story_arc>
  <desired_cta>${concept.cta}</desired_cta>
  <framework_lever>${concept.framework}</framework_lever>
  <why_this_why_now>${concept.whyThisWhyNow}</why_this_why_now>
  <predicted_engagement>${(concept.predictedEngagementRange[0] * 100).toFixed(1)}–${(concept.predictedEngagementRange[1] * 100).toFixed(1)}%</predicted_engagement>
  <risk_level>${concept.riskLevel}</risk_level>
  <cost_budget>$${concept.costEstimate.toFixed(2)}</cost_budget>
</concept_brief>

Think through the 4-step creative process, then output the JSON. Make this asset unmistakably ${ctx.businessName}'s — no competitor could claim it.`.trim();

  return { system, user };
}

// ---------------------------------------------------------------------------
// Autonomy modes — thresholds the backend enforces
// ---------------------------------------------------------------------------

const AUTONOMY_MODES = {
  full_autopilot: {
    label: 'Full Autopilot',
    description:
      'AI publishes when quality ≥95. Best for mature brands with established voice. +23% engagement in beta (catches trend waves, less second-guessing).',
    autoPublishThreshold: 95,
    requireApprovalBelow: 95,
  },
  hybrid: {
    label: 'Hybrid (recommended default)',
    description:
      'You approve within 4 business hours; after that, quality ≥90 auto-publishes. Quality ≥95 auto-publishes immediately. Captures 78% of trend-wave peak engagement.',
    autoPublishThreshold: 95,
    fallbackAutoPublishAfterHours: 4,
    fallbackThreshold: 90,
  },
  approve_everything: {
    label: 'Approve Everything',
    description:
      'All posts require explicit approval. Recommended for regulated industries (legal, medical, finance) and early-stage accounts still defining voice.',
    autoPublishThreshold: null,
  },
};

// ---------------------------------------------------------------------------
// Guardrails the backend enforces server-side (documented here for clarity)
// ---------------------------------------------------------------------------

const WF1_GUARDRAILS = {
  volume: {
    maxPostsPerPlatformPerDay: 3,
    minMinutesBetweenSamePlatform: 240,
    storiesMaxPerDay: 10,
  },
  topicCooldownDays: 0,
  trendingExceptionHalfLifeHours: 24,
  crisisAutoPause: {
    triggers: ['natural_disaster', 'public_figure_death', 'major_tragedy', 'contentious_election_day'],
    resumeAfterSentimentNormalizes: true,
    typicalDurationHours: [24, 72],
  },
  holidaySensitivity: {
    ramadanNoFoodPromoInDaylight: true,
    respectDaysOfMourning: true,
    adjustToneForSolemnHolidays: true,
  },
  costPerPostBudgetUsd: {
    image: 0.15,
    carousel: 0.35,
    reel: 0.65,
    tiktok: 0.45,
    linkedinArticle: 0.25,
  },
  monthlyCapUsd: {
    growth: 45, // ~100 pieces
    agency: 180, // ~400 pieces
  },
};


// ── CommonJS exports ──
module.exports.PLATFORM_GENERATION_SPECS = PLATFORM_GENERATION_SPECS;
module.exports.AUTONOMY_MODES = AUTONOMY_MODES;
module.exports.WF1_GUARDRAILS = WF1_GUARDRAILS;
module.exports.buildStrategicDecisionPrompt = buildStrategicDecisionPrompt;
module.exports.buildPlatformGenerationPrompt = buildPlatformGenerationPrompt;
