/*
 * AUTOGENERATED FROM workflow_2_lead_scoring.ts — DO NOT EDIT BY HAND
 * Source: ../maroa-ai-marketing-automator/src/lib/prompts/workflow_2_lead_scoring.ts
 * Regenerate: node scripts/sync_foundation.mjs
 * --------------------------------------------------------------------------- 
 * Source SHA-256 (first 12): c812ec7ddecd
 */
'use strict';

/**
 * Workflow #2 — Lead Scoring & Routing (B2B-Optimized)
 * ============================================================================
 * Senior RevOps system. Behavioral signals dominate (35% weight) because
 * what leads DO predicts purchase 5x more accurately than what they CLAIM
 * on forms (Marketo research 2021, replicated 2024).
 *
 * Per MAROA_15_WORKFLOWS_V2 section "WORKFLOW #2 — LEAD SCORING & ROUTING".
 * ============================================================================
 */

const { buildSystemPrompt } = require('./foundation.js');

// ---------------------------------------------------------------------------
// Enrichment pipeline output — what the scorer operates on
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Scoring output
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Deterministic scorer — runs server-side. Doesn't require LLM.
// The LLM is used for response generation (below) and for edge cases where
// the deterministic model is uncertain.
// ---------------------------------------------------------------------------

function scoreLead(p) {
  const notesDemo = [];
  const notesBeh = [];
  const notesCo = [];
  const notesCom = [];

  // Demographic fit (0–20 raw, then scaled by 1.0 into the 20-pt bucket)
  let icpMatch = 0;
  const titleMatch = !!p.person?.title && p.icp.idealTitles.some((t) =>
    p.person.title.toLowerCase().includes(t.toLowerCase()),
  );
  const sizeMatch =
    !!p.company?.employeeCount &&
    (!p.icp.idealCompanySizeMin || p.company.employeeCount >= p.icp.idealCompanySizeMin) &&
    (!p.icp.idealCompanySizeMax || p.company.employeeCount <= p.icp.idealCompanySizeMax);
  const industryMatch =
    !!p.company?.industryNaics &&
    p.icp.idealIndustries.some((i) =>
      p.company.industryNaics.toLowerCase().includes(i.toLowerCase()),
    );
  const fitCount = [titleMatch, sizeMatch, industryMatch].filter(Boolean).length;
  if (fitCount === 3) {
    icpMatch = 20;
    notesDemo.push('Exact ICP match (title + size + industry)');
  } else if (fitCount === 2) {
    icpMatch = 15;
    notesDemo.push('Strong fit (2 of 3 ICP dimensions)');
  } else if (fitCount === 1) {
    icpMatch = 8;
    notesDemo.push('Partial fit (1 of 3 ICP dimensions)');
  } else {
    notesDemo.push('No clear ICP fit');
  }

  let roleAuthority = 0;
  switch (p.person?.seniority) {
    case 'c_suite':
      roleAuthority = 5;
      notesDemo.push('Final decision maker (C-suite/owner)');
      break;
    case 'vp':
    case 'director':
      roleAuthority = 3;
      notesDemo.push('Key influencer (VP/Director)');
      break;
    case 'manager':
    case 'senior_ic':
      roleAuthority = 2;
      notesDemo.push('Evaluator (manager/senior IC)');
      break;
    case 'gatekeeper':
      roleAuthority = -3;
      notesDemo.push('Gatekeeper — likely research, not buying');
      break;
    default:
      roleAuthority = 0;
  }

  const demographicFitRaw = icpMatch + roleAuthority; // up to ~25, clamp
  const demographicFit = Math.max(0, Math.min(20, demographicFitRaw));

  // Behavioral intent (0–35)
  let buyingStageSignals = 0;
  if (p.behavior.pricingPageVisits >= 1) {
    buyingStageSignals += p.behavior.pricingPageVisits >= 3 ? 15 : 10;
    notesBeh.push(
      `Pricing page visited ${p.behavior.pricingPageVisits}× (${p.behavior.pricingPageTimeSeconds}s)`,
    );
  }
  if (p.behavior.demoPageVisited) {
    buyingStageSignals += 10;
    notesBeh.push('Demo page visited');
  }
  if (p.behavior.comparisonPageVisited) {
    buyingStageSignals += 12;
    notesBeh.push('Comparison page visited');
  }
  if (p.behavior.integrationPageVisited) {
    buyingStageSignals += 8;
    notesBeh.push('Integration page visited');
  }
  if (p.behavior.caseStudiesDownloaded > 0) {
    buyingStageSignals += 7;
    notesBeh.push(`${p.behavior.caseStudiesDownloaded} case study downloads`);
  }
  if (p.behavior.contactSalesFormSubmitted) {
    buyingStageSignals += 20;
    notesBeh.push('Contact sales form submitted');
  }
  if (p.behavior.emailReplies > 0) {
    buyingStageSignals += 15;
    notesBeh.push('Replied to email — high intent signal');
  }
  if (p.behavior.webinarAttended) {
    buyingStageSignals += 10;
    notesBeh.push('Attended webinar');
  }
  if (p.behavior.sessionDepthMax >= 5) {
    buyingStageSignals += 8;
    notesBeh.push(`Deep session (${p.behavior.sessionDepthMax} pages)`);
  }
  if (p.behavior.calendarLinkClicked) {
    buyingStageSignals += 20;
    notesBeh.push('Clicked calendar link');
  }

  let engagementVelocity = 0;
  if (p.behavior.activityLast24h) {
    engagementVelocity += 10;
    notesBeh.push('Active in last 24h');
  } else if (p.behavior.activityLast7d) {
    engagementVelocity += 5;
    notesBeh.push('Active in last 7d');
  } else if (p.behavior.dormantDays >= 30) {
    engagementVelocity -= 5;
    notesBeh.push(`Dormant ${p.behavior.dormantDays} days`);
  }

  const behRaw = buyingStageSignals + engagementVelocity;
  const behavioralIntent = Math.max(0, Math.min(35, behRaw));

  // Company fit (0–25)
  let coPositive = 0;
  let coNegative = 0;
  if (sizeMatch) {
    coPositive += 15;
    notesCo.push('Company size in ICP range');
  }
  if (industryMatch) {
    coPositive += 10;
    notesCo.push('Industry in ICP');
  }
  const recentFunding =
    p.company?.fundingHistory?.some(
      (f) => Date.now() - new Date(f.closedAt).getTime() < 365 * 24 * 60 * 60 * 1000,
    ) ?? false;
  if (recentFunding) {
    coPositive += 8;
    notesCo.push('Recently funded (last 12mo) — expansion budget');
  }
  if ((p.company?.employeeGrowthYoy ?? 0) > 0.3) {
    coPositive += 7;
    notesCo.push('Employee growth >30% YoY');
  }

  const domain = p.email.split('@')[1]?.toLowerCase() ?? '';
  if (p.icp.deadbeatList.some((d) => domain.includes(d.toLowerCase()))) {
    coNegative -= 20;
    notesCo.push('Domain in deadbeat list');
  }
  if (p.icp.idealCompanySizeMin && (p.company?.employeeCount ?? 0) < p.icp.idealCompanySizeMin) {
    coNegative -= 10;
    notesCo.push('Size below ICP floor');
  }
  const geoServed =
    !p.icp.servedGeographies.length ||
    p.icp.servedGeographies.some(
      (g) =>
        p.company?.hq?.country?.toLowerCase().includes(g.toLowerCase()) ||
        p.person?.location?.country?.toLowerCase().includes(g.toLowerCase()),
    );
  if (!geoServed) {
    coNegative -= 10;
    notesCo.push('Geography not served');
  }

  const coRaw = coPositive + coNegative;
  const companyFit = Math.max(0, Math.min(25, coRaw));

  // Commitment signals (0–20)
  let messageQuality = 0;
  if (p.intake?.specificProductQuestion) {
    messageQuality += 10;
    notesCom.push('Specific product question');
  }
  if (p.intake?.useCaseDescribed) {
    messageQuality += 8;
    notesCom.push('Clear use case described');
  }
  if (p.intake?.timelineMentioned) {
    messageQuality += 12;
    notesCom.push('Timeline mentioned');
  }
  if (p.intake?.budgetMentioned) {
    messageQuality += 15;
    notesCom.push('Budget mentioned');
  }
  if (p.intake?.competitiveEvaluationMentioned) {
    messageQuality += 10;
    notesCom.push('Competitive evaluation mentioned');
  }
  if (p.intake?.message && p.intake.message.length < 15 && !p.intake.specificProductQuestion) {
    messageQuality -= 5;
    notesCom.push('Vague "info please" message');
  }

  let verification = 0;
  if (!p.personalEmail && !p.roleEmail) {
    verification += 8;
    notesCom.push('Business email');
  }
  if (p.person?.linkedinUrl) {
    verification += 5;
    notesCom.push('LinkedIn profile verified');
  }
  if (p.behavior.calendarLinkClicked) {
    verification += 20;
  }

  const comRaw = messageQuality + verification;
  const commitmentSignals = Math.max(0, Math.min(20, comRaw));

  // Total
  const total = Math.round(
    demographicFit + behavioralIntent + companyFit + commitmentSignals,
  );

  // Tier
  let tier ;
  if (total >= 80) tier = 'hot';
  else if (total >= 60) tier = 'warm_high';
  else if (total >= 40) tier = 'warm';
  else if (total >= 20) tier = 'cool';
  else tier = 'junk';

  // Top signals extraction
  const topPredictiveSignals = [
    ...notesBeh.filter((n) => /pricing|comparison|contact sales|replied|calendar|demo/.test(n)),
    ...notesCo.filter((n) => /funded|growth/.test(n)),
    ...notesCom.filter((n) => /budget|timeline/.test(n)),
  ].slice(0, 5);

  const topRiskSignals = [
    ...notesCo.filter((n) => /deadbeat|below|not served/.test(n)),
    ...notesCom.filter((n) => /vague/.test(n)),
    ...notesDemo.filter((n) => /Gatekeeper/.test(n)),
  ];

  const recommendedAction = tierActionRecommendation(tier);

  return {
    leadId: p.leadId,
    total,
    tier,
    components: {
      demographicFit: {
        score: demographicFit,
        icpMatch,
        roleAuthority,
        notes: notesDemo,
      },
      behavioralIntent: {
        score: behavioralIntent,
        buyingStageSignals,
        engagementVelocity,
        notes: notesBeh,
      },
      companyFit: {
        score: companyFit,
        positive: coPositive,
        negative: coNegative,
        notes: notesCo,
      },
      commitmentSignals: {
        score: commitmentSignals,
        messageQuality,
        verification,
        notes: notesCom,
      },
    },
    topPredictiveSignals,
    topRiskSignals,
    recommendedAction,
    scoredAt: new Date().toISOString(),
  };
}

function tierActionRecommendation(tier) {
  switch (tier) {
    case 'hot':
      return 'Respond within 5 minutes (9x conversion lift — HBR). Draft personalized message with research. Auto-suggest meeting times.';
    case 'warm_high':
      return 'Same-day response (1h window). AI draft + nurture if no response within 24h.';
    case 'warm':
      return '24h response window. Enroll in automated nurture sequence (WF7). Email + retargeting audience.';
    case 'cool':
      return 'Long-term nurture. Monthly newsletter only. Trigger re-engagement on behavior change.';
    case 'junk':
      return 'Flag and file. Weekly review. Never delete — a mis-flag teaches the model.';
  }
}

// ---------------------------------------------------------------------------
// LLM response generation prompt — hot/warm-high leads get a personalized draft
// ---------------------------------------------------------------------------

function buildLeadResponsePrompt(
  ctx,
  lead,
  score,
) {
  const addendum = `
WORKFLOW #2 — LEAD SCORING, RESPONSE GENERATION PHASE

You are the founder's SDR with 10 years at a top-performing B2B sales org.
A lead just came in and the scoring engine classified them as ${score.tier.toUpperCase()}
(${score.total}/100). Your job: draft a first-touch message that feels like
it was written by a smart human who actually read their profile.

HARD RULES
- 80–200 words. Any longer and they won't read; any shorter and it feels lazy.
- NEVER start with "Hi {{name}}, I see you're a [title]..." — that's dead on arrival.
- Open with GENUINE personalization from the enrichment payload: a specific
  detail only a real reader would notice (their company's recent funding,
  their tenure at the role, a behavior they took on our site).
- Reference a SPECIFIC behavior they took: "I saw you were looking at our
  pricing and comparison with [competitor] yesterday…"
- Offer IMMEDIATE value before asking for anything. One sentence of concrete
  help, not a platitude.
- Low-friction CTA: give them permission to ignore it. "If this is relevant,
  grab 15 min here: [CAL_LINK]. If not, just ignore and I won't bug you."
- Signature with quiet social proof: the founder's name + "previously helped
  [N]+ teams at [peer companies]".

QUALITY GATES (scored before send — must clear all)
- Personalization specificity: 0–100, must be >70. Reference at least 2
  unique facts from enrichment.
- Length: 80–200 words.
- CTA clarity: exactly one action, with a fallback.
- Tone match: matches brand voice (see BRAND CONTEXT above).
- No typos, no AI-ese ("I hope this email finds you well"), no superlatives
  without evidence.

PSYCHOLOGY LEVERS TO CONSIDER
- Reciprocity (Cialdini): open with a gift — a specific insight, a Loom
  link, a cheat-sheet. Before asking.
- Authority (Cialdini): quiet signals in the signature — not "I'm the best
  in the industry" but "previously helped 200+ teams at [peer brands]".
- Liking (Cialdini): genuine compliments are rare and powerful when tied
  to something specific they did publicly.
- Low-friction CTA (Kahneman): give the opt-out explicitly. It removes
  the defensive reading and raises response rate.
- StoryBrand: the prospect is the hero. You are the guide. Name the stakes
  (what they'll hit if unaddressed) and the transformation briefly.

OUTPUT FORMAT: strict JSON
{
  "subject": string,            // 30–60 chars, specific
  "body": string,               // 80–200 words, markdown
  "personalizationScore": number,  // self-assessed 0–100
  "qualityChecks": {
    "personalization": number,   // 0–100
    "length": boolean,           // 80–200 words?
    "ctaClarity": boolean,
    "toneMatch": boolean,
    "noTypos": boolean
  },
  "predictedResponseRate": { "low": number, "high": number },  // as decimals
  "psychologyLevers": string[],  // 1–3 you used, by name
  "frameworkJustification": string // 1–2 sentences naming WHY these levers
}
`.trim();

  const user = `
LEAD
  Tier: ${score.tier.toUpperCase()} (${score.total}/100)
  Top predictive signals: ${score.topPredictiveSignals.join(' | ') || '(none)'}
  Top risk signals: ${score.topRiskSignals.join(' | ') || '(none)'}

PERSON
  ${JSON.stringify(lead.person ?? {}, null, 2)}

COMPANY
  ${JSON.stringify(lead.company ?? {}, null, 2)}

BEHAVIOR
  ${JSON.stringify(lead.behavior, null, 2)}

INTAKE MESSAGE
  ${lead.intake?.message ?? '(none)'}

INTENT SIGNALS
  ${JSON.stringify(lead.intentSignals ?? {}, null, 2)}

SIGNATURE CONTEXT
  Founder name + role from BRAND CONTEXT.
`.trim();

  return {
    system: buildSystemPrompt(ctx, addendum),
    user,
  };
}

// ---------------------------------------------------------------------------
// Routing rules — territory + expertise + workload
// ---------------------------------------------------------------------------

function routeLead(
  lead,
  score,
  rules,
  currentLoads,
) {
  for (const rule of rules) {
    const decision = tryRule(lead, score, rule, currentLoads);
    if (decision) return decision;
  }
  return {
    leadId: lead.leadId,
    ownerId: null,
    rationale: 'No routing rule matched — falling back to shared queue',
    matchedRule: 'round_robin',
    slaMinutes: slaForTier(score.tier),
  };
}

function tryRule(
  lead,
  score,
  rule,
  currentLoads,
) {
  switch (rule.kind) {
    case 'account_based': {
      const domain = lead.email.split('@')[1]?.toLowerCase() ?? '';
      const owner = rule.accountOwnerMap[domain];
      if (owner) {
        return {
          leadId: lead.leadId,
          ownerId: owner,
          rationale: `Account-based: ${domain} mapped to ${owner}`,
          matchedRule: 'account_based',
          slaMinutes: slaForTier(score.tier),
        };
      }
      return null;
    }
    case 'territory': {
      const country = lead.company?.hq?.country ?? lead.person?.location?.country;
      const match = rule.rules.find(
        (r) => r.country && country && r.country.toLowerCase() === country.toLowerCase(),
      );
      if (match) {
        return {
          leadId: lead.leadId,
          ownerId: match.ownerId,
          rationale: `Territory: ${country} → ${match.ownerId}`,
          matchedRule: 'territory',
          slaMinutes: slaForTier(score.tier),
        };
      }
      return null;
    }
    case 'industry': {
      const ind = lead.company?.industryNaics?.toLowerCase();
      const match = rule.rules.find((r) => ind && ind.includes(r.industry.toLowerCase()));
      if (match) {
        return {
          leadId: lead.leadId,
          ownerId: match.ownerId,
          rationale: `Industry expertise: ${ind} → ${match.ownerId}`,
          matchedRule: 'industry',
          slaMinutes: slaForTier(score.tier),
        };
      }
      return null;
    }
    case 'deal_size': {
      const acv = estimateDealSize(lead);
      const ordered = [...rule.rules].sort((a, b) => b.minAcv - a.minAcv);
      const match = ordered.find((r) => acv >= r.minAcv);
      if (match) {
        return {
          leadId: lead.leadId,
          ownerId: match.ownerId,
          rationale: `Deal size $${acv.toLocaleString()} matched tier ≥$${match.minAcv.toLocaleString()}`,
          matchedRule: 'deal_size',
          slaMinutes: slaForTier(score.tier),
        };
      }
      return null;
    }
    case 'workload_balanced': {
      const eligible = rule.owners
        .map((o) => ({ owner: o, load: currentLoads[o] ?? 0 }))
        .filter((e) => e.load < rule.maxActiveLeads)
        .sort((a, b) => a.load - b.load);
      if (eligible.length) {
        return {
          leadId: lead.leadId,
          ownerId: eligible[0].owner,
          rationale: `Workload-balanced: ${eligible[0].owner} has ${eligible[0].load} active leads`,
          matchedRule: 'workload_balanced',
          slaMinutes: slaForTier(score.tier),
        };
      }
      return null;
    }
    case 'round_robin': {
      if (rule.owners.length === 0) return null;
      const sorted = rule.owners
        .map((o) => ({ owner: o, load: currentLoads[o] ?? 0 }))
        .sort((a, b) => a.load - b.load);
      return {
        leadId: lead.leadId,
        ownerId: sorted[0].owner,
        rationale: `Round robin to least-loaded owner (${sorted[0].load} active)`,
        matchedRule: 'round_robin',
        slaMinutes: slaForTier(score.tier),
      };
    }
  }
}

function slaForTier(tier) {
  switch (tier) {
    case 'hot':
      return 5;
    case 'warm_high':
      return 60;
    case 'warm':
      return 24 * 60;
    case 'cool':
      return 7 * 24 * 60;
    case 'junk':
      return 30 * 24 * 60;
  }
}

function estimateDealSize(lead) {
  const size = lead.company?.employeeCount ?? 0;
  if (size >= 1000) return 150_000; // enterprise
  if (size >= 200) return 40_000; // mid-market
  if (size >= 50) return 12_000; // SMB+
  if (size >= 10) return 4_000; // small
  return 1_000;
}

// ---------------------------------------------------------------------------
// Buying committee detection (B2B)
// ---------------------------------------------------------------------------

function detectBuyingCommittee(leads, scores) {
  const byDomain = new Map();
  for (const l of leads) {
    const domain = l.email.split('@')[1]?.toLowerCase() ?? '';
    if (!domain || l.roleEmail || l.personalEmail) continue;
    if (!byDomain.has(domain)) byDomain.set(domain, []);
    byDomain.get(domain).push(l);
  }
  const committees = [];
  for (const [domain, ls] of byDomain.entries()) {
    if (ls.length < 2) continue; // single contact ≠ committee
    const sorted = ls.sort((a, b) => a.createdAt.localeCompare(b.createdAt));
    const totalScore = ls.reduce(
      (sum, l) => sum + (scores.find((s) => s.leadId === l.leadId)?.total ?? 0),
      0,
    );
    committees.push({
      companyDomain: domain,
      members: sorted.map((l) => ({
        leadId: l.leadId,
        role: inferCommitteeRole(l),
        seniority: l.person?.seniority ?? 'unknown',
        name: `${l.person?.firstName ?? ''} ${l.person?.lastName ?? ''}`.trim(),
        title: l.person?.title ?? '',
      })),
      firstContactAt: sorted[0].createdAt,
      lastActivityAt: sorted[sorted.length - 1].createdAt,
      totalActivityScore: totalScore,
      isActiveDeal: totalScore > 100,
    });
  }
  return committees;
}

function inferCommitteeRole(l) {
  const title = (l.person?.title ?? '').toLowerCase();
  if (l.person?.seniority === 'c_suite') return 'economic_buyer';
  if (title.includes('engineer') || title.includes('architect') || title.includes('technical'))
    return 'technical_evaluator';
  if (title.includes('ops') || title.includes('admin') || title.includes('user'))
    return 'user';
  if (l.person?.seniority === 'vp' || l.person?.seniority === 'director') return 'champion';
  return 'influencer';
}

// ---------------------------------------------------------------------------
// Hybrid approval config (per spec)
// ---------------------------------------------------------------------------

const WF2_HYBRID_APPROVAL = {
  hotLeadDraftWindowMinutes: 10,
  autoSendIfConfidenceAbove: 0.9,
  waitForHumanIfConfidenceBetween: [0.8, 0.89],
  responseTimeAdvantageHbrMultiplier: 9, // 9x conversion lift when responding within 5 min
};


// ── Auto-generated CommonJS exports (sync_foundation.mjs) ──
module.exports.WF2_HYBRID_APPROVAL = WF2_HYBRID_APPROVAL;
module.exports.scoreLead = scoreLead;
module.exports.buildLeadResponsePrompt = buildLeadResponsePrompt;
module.exports.routeLead = routeLead;
module.exports.estimateDealSize = estimateDealSize;
module.exports.detectBuyingCommittee = detectBuyingCommittee;
