/*
 * AUTOGENERATED FROM workflow_4_reviews.ts — DO NOT EDIT BY HAND
 * Source: ../maroa-ai-marketing-automator/src/lib/prompts/workflow_4_reviews.ts
 * Regenerate: node scripts/sync_foundation.mjs
 * --------------------------------------------------------------------------- 
 * Source SHA-256 (first 12): 390e19a78ad9
 */
'use strict';

/**
 * Workflow #4 — Review Response & Reputation Engine
 * ============================================================================
 * Chief Experience Officer-grade. Every review is a conversation with 100
 * future customers.
 *
 * Business case (from spec):
 *   - 88% of consumers trust online reviews as much as personal recommendations
 *     (BrightLocal 2024).
 *   - 3.5→4.0 stars = +12% revenue (HBS study).
 *   - >50% response rate = +21% revenue vs non-responders (BrightLocal).
 *   - 30–45% of customers UPDATE negative reviews when business responds
 *     thoughtfully (Harvard research).
 *
 * Per MAROA_15_WORKFLOWS_V2 section "WORKFLOW #4".
 * ============================================================================
 */

const { buildSystemPrompt } = require('./foundation.js');

// ---------------------------------------------------------------------------
// Classification (done server-side with LLM; this prompt defines the schema)
// ---------------------------------------------------------------------------

function buildReviewClassificationPrompt(review) {
  const system = `
You are a Chief Experience Officer's review triage analyst. Given a review,
classify it into the schema below. Be conservative — if unsure, escalate.

RULES
- Category: positive (4–5⭐ + positive language), neutral (3⭐ or mixed),
  negative (1–2⭐), critical (1⭐ + accusation, legal threat, safety, fraud).
- Urgency:
    immediate (<1h): legal threats, safety issues, viral risk, extortion
    high (<6h):      detailed negative with specifics, influential reviewer
    medium (<24h):   standard negative, neutral with feedback
    low (<48h):      positive, routine
- Sentiment: -1 (strongly negative) to 1 (strongly positive).
- Topics: pick from product_quality, customer_service, price_value,
  shipping_delivery, staff_interaction, cleanliness, wait_time,
  communication, expertise, outcome_results. Max 3.
- Authenticity flags (the "fake/suspicious" patterns):
  * day_old_account — reviewer account <7 days old
  * single_review — this is reviewer's only review on the platform
  * generic_language — no specific details a real customer would know
  * clustered_timing — similar to other suspicious reviews in window
  * competitor_signature — language matches known competitor-sabotage patterns
  * geographic_inconsistency — reviewer location doesn't match business market
- isSuspicious: true if authenticity.score < 40.
- Legal exposure: true if the review contains one of the risk patterns.
- DEFAMATION: false statement of fact (not opinion) about the business.
- EXTORTION: "pay me or I'll leave more bad reviews."
- REGULATORY CLAIMS: FTC, FDA, medical, financial advice claims.
- SAFETY: health, injury, foodborne illness, physical harm.
- DISCRIMINATION: protected-class claims under anti-discrimination law.

OUTPUT FORMAT: strict JSON matching ReviewClassificationResult.
`.trim();

  const user = `
PLATFORM: ${review.platform}
RATING: ${review.rating}/5
REVIEWER: ${review.reviewerName}${review.reviewerAccountAgeDays != null ? ` (account ${review.reviewerAccountAgeDays}d old)` : ''}${review.reviewerReviewCount != null ? ` — ${review.reviewerReviewCount} prior reviews` : ''}
LOCATION: ${review.reviewerLocation ?? 'unknown'}
TITLE: ${review.title ?? '(none)'}
BODY:
${review.body}

Classify.
`.trim();

  return { system, user };
}

// ---------------------------------------------------------------------------
// Response generation prompts — per category
// ---------------------------------------------------------------------------

function buildReviewResponsePrompt(
  ctx,
  review,
) {
  const addendum = `
WORKFLOW #4 — REVIEW RESPONSE, CATEGORY = ${review.category.toUpperCase()}

You are a Chief Experience Officer at ${ctx.businessName}. A review has been
classified as ${review.category.toUpperCase()} with ${review.urgency.toUpperCase()}
urgency on ${review.platform}. Draft a response that meets senior-brand
standard. Every word matters — this response is read by 100 future customers.

CATEGORY PHILOSOPHY
${categoryPhilosophy(review.category)}

UNIVERSAL RULES (apply to every response)
- Use the reviewer's first name. Not "Dear valued customer".
- Signature: owner/manager name + title. Never "the team".
- Brand voice match: honor BRAND CONTEXT above — tone, vocabulary, banned words.
- NEVER start with "However" or "Actually".
- NEVER copy-paste language across reviews.
- Reference at least one specific detail the reviewer mentioned.
- If the review is in a non-English language, respond in that language.
- Match the region's cultural formality expectations.

${review.category === 'positive' ? positiveRules() : ''}
${review.category === 'neutral' ? neutralRules() : ''}
${review.category === 'negative' ? negativeRules() : ''}
${review.category === 'critical' ? criticalRules() : ''}

QUALITY GATES (enforced)
- Personalization specificity: >70/100 (must reference specific details).
- Brand voice match: >85/100.
- Length: see per-category rules.
- No AI-ese ("thank you for your valuable feedback").
- Signature with name + title.
- Negative/critical: MUST include offline redirect (email or phone).

PSYCHOLOGY LEVERS (name which you use, load-bearing only)
- Reciprocity — specific upgrade offer, free next visit, gift
- Authority — expertise reference ("our chef developed over 2 years")
- Liking — genuine compliment + shared identity
- Commitment — "next time" language creates micro-commitment to return
- Social proof — referencing "the kind of thing other guests notice"
- Peak-end rule — offer to engineer a peak experience next time (Kahneman)
- StoryBrand — customer is the hero, you are the guide offering the plan

OUTPUT FORMAT: strict JSON matching ReviewResponseOutput TypeScript interface.
${review.category === 'negative' ? 'Return 2–3 variants in the `variants` array for owner selection.' : ''}
${review.category === 'critical' ? 'Return 1 primary response PLUS escalation note (do not auto-publish).' : ''}
`.trim();

  const user = `
REVIEW TO RESPOND TO
  Platform: ${review.platform}
  Rating: ${review.rating}/5
  Reviewer: ${review.reviewerName}
  Language: ${review.language}
  Topics detected: ${review.topics.join(', ') || '(none)'}
  Sentiment: ${review.sentiment.toFixed(2)}
  Authenticity: ${review.authenticity.score}/100 ${review.authenticity.isSuspicious ? '⚠ SUSPICIOUS' : ''}
  Legal flags: ${JSON.stringify(review.legalExposure)}

  Title: ${review.title ?? '(none)'}
  Body:
${review.body}

Draft response now.
`.trim();

  return {
    system: buildSystemPrompt(ctx, addendum),
    user,
  };
}

function categoryPhilosophy(cat) {
  switch (cat) {
    case 'positive':
      return `POSITIVE REVIEW PHILOSOPHY
Amplify the positive. Subtly reinforce what made them happy. Invite
continued engagement. NEVER generic "Thanks!". Name the specific thing
they praised. Add a brief brand moment (what makes this special to us).
Offer a gentle forward invitation (return, try something new, share).`;
    case 'neutral':
      return `NEUTRAL REVIEW PHILOSOPHY
These are gold. The customer had a meh experience. The right response
can move them to 4–5 stars. Acknowledge the meh honestly — show you
heard the specific issues. Offer a specific path to a better next
experience. Concrete action, not vague "we'll do better".`;
    case 'negative':
      return `NEGATIVE REVIEW PHILOSOPHY
Empathize first, don't justify. Take ownership — even if 30% our fault,
take 100% in the reply. Customers smell defensive responses. Get offline
fast — "let's make this right, email me at…". Never argue details
publicly — future customers read this. Brevity: 60–120 words. Long
defensive responses look worse than the original negative. Personal
signature: owner/manager name, not "the team".`;
    case 'critical':
      return `CRITICAL REVIEW PHILOSOPHY
Never auto-publish. Flag to owner + 3 stakeholders immediately. Draft
is careful, legally-aware language ("we take this seriously, contacting
you privately"). Suggest platform dispute if defamatory + false.
Recommend legal counsel consultation if warranted.`;
  }
}

function positiveRules() {
  return `
POSITIVE SPECIFIC RULES
- Length: 40–80 words (respected but not excessive).
- Structure: (1) specific appreciation, (2) brief brand moment,
  (3) gentle forward invitation.
- Name the specific thing they praised.
- Human detail: mention a team member by first name if possible.
- Subtle upgrade offer allowed (not required).
- Reciprocity + commitment levers appropriate here.
`.trim();
}

function neutralRules() {
  return `
NEUTRAL SPECIFIC RULES
- Length: 50–100 words.
- Structure: (1) thank for honest feedback, (2) acknowledge specific
  issue, (3) action taken or offered, (4) invitation to return.
- Concrete action or offer — not vague "we'll improve".
- Personal ownership, not corporate-speak.
- Offline redirect offered but not demanded.
`.trim();
}

function negativeRules() {
  return `
NEGATIVE SPECIFIC RULES
- Length: 60–120 words MAXIMUM.
- Open with "I'm sorry you had this experience" (or cultural equivalent).
- Take 100% ownership. No excuses. No "however".
- Name the specific issue they raised.
- State the action taken (even if just "passed to operations team").
- Offline redirect with owner's email or direct phone.
- Personal signature with name and title.
- Generate 2–3 variants for owner selection.
- NEVER argue details publicly.
`.trim();
}

function criticalRules() {
  return `
CRITICAL SPECIFIC RULES
- DO NOT AUTO-PUBLISH. Mark response as "awaiting_approval" always.
- Length: 50–100 words.
- Language is legally aware. Avoid admissions of liability.
- "We take this seriously and are reaching out privately."
- Redirect to owner's direct line immediately.
- Flag for legal counsel review if the situation warrants.
- Platform dispute recommendation included if defamation suspected.
`.trim();
}

// ---------------------------------------------------------------------------
// Review request automation (for earning new reviews)
// ---------------------------------------------------------------------------

function buildReviewRequestPrompt(
  ctx,
  customer,
  trigger,
) {
  const addendum = `
WORKFLOW #4 — REVIEW REQUEST GENERATION

Goal: earn a new review from a happy customer. Respectful, easy, single-ask.

HARD RULES
- Short. SMS: 160 chars max. Email: 80 words max. WhatsApp: 120 chars max.
- First name personalization.
- Single deep link to the review platform — no 6-step instructions.
- Ask once, no nag. If they don't act, don't follow up.
- Channel appropriate tone (SMS more casual than email).
- Always include a low-friction opt-out.
- Mention the specific product/service/visit they had.

PSYCHOLOGY
- Reciprocity: remind of the good experience briefly ("glad Marco took care of you").
- Commitment: "a quick 30 seconds" frames it as small.
- Social proof is EARNED here, not required — the review itself IS the proof.
- Liking: sincere thanks, not formula.

OUTPUT FORMAT
{
  "message": string,        // the body
  "deepLink": string,       // placeholder — backend injects actual URL
  "channel": "${trigger.channel}",
  "characterCount": number,
  "predictedConversionRate": number  // 0-1
}
`.trim();

  const user = `
CUSTOMER: ${customer.name}
PRODUCT/SERVICE: ${customer.product ?? customer.service ?? 'their recent visit'}
STAFF MEMBER: ${customer.staffMember ?? 'n/a'}
CHANNEL: ${trigger.channel}
PLATFORM (target): ${trigger.platform}
TRIGGER: ${trigger.kind} (delay: ${trigger.delayHours}h)
`.trim();

  return {
    system: buildSystemPrompt(ctx, addendum),
    user,
  };
}

// ---------------------------------------------------------------------------
// Dispute drafting (for fake reviews)
// ---------------------------------------------------------------------------

function buildDisputePrompt(
  ctx,
  review,
  evidence,
) {
  const addendum = `
WORKFLOW #4 — PLATFORM DISPUTE GENERATION

Draft a platform-specific dispute for a review we believe is fake or
malicious. The tone is professional, evidence-led, not emotional. These
disputes are reviewed by platform ops teams who see thousands per week —
make ours easy to approve.

REQUIRED SECTIONS
1. Opening: one sentence stating why this review violates platform policy.
2. Evidence list: bulleted, each item factual and verifiable.
3. Business impact statement (brief).
4. Requested action: removal OR investigation.
5. Professional sign-off.

DO NOT
- Attack the reviewer personally.
- Speculate about motives beyond what evidence supports.
- Use emotional language.

OUTPUT FORMAT: strict JSON { subject, body, evidenceItems: string[], requestedAction: "removal" | "investigation" }
`.trim();

  const user = `
REVIEW
  Platform: ${review.platform}
  Reviewer: ${review.reviewerName}
  Rating: ${review.rating}/5
  Body: ${review.body}

EVIDENCE
  Reviewer account age: ${evidence.reviewerAccountAge} days
  Reviewer history: ${evidence.reviewerHistory} reviews total
  Clustered suspicious timings: ${evidence.clusteredTimings.join(', ') || '(none)'}
  Transaction verification: ${evidence.transactionVerification}
  Content flags: ${evidence.contentFlags.join(', ') || '(none)'}
`.trim();

  return {
    system: buildSystemPrompt(ctx, addendum),
    user,
  };
}

// ---------------------------------------------------------------------------
// Reputation dashboard aggregation shape
// ---------------------------------------------------------------------------

const WF4_GUARDRAILS = {
  platformCheckCadenceMinutes: {
    primary: 60, // every hour
    secondary: 24 * 60, // daily
  },
  responseSla: {
    immediate: 60, // minutes
    high: 6 * 60,
    medium: 24 * 60,
    low: 48 * 60,
  },
  autoPublishPositiveThreshold: 85, // brand voice score
  criticalAlwaysRequiresApproval: true,
  negativeAlwaysRequiresApproval: true, // per spec "your choice"
  generateVariantsFor: ['negative', 'critical'],
  variantsCount: 3,
  lengthLimits: {
    positive: { min: 40, max: 80 },
    neutral: { min: 50, max: 100 },
    negative: { min: 60, max: 120 },
    critical: { min: 50, max: 100 },
  },
  legalCounselRecommendedIf: [
    'defamationRisk',
    'extortionRisk',
    'regulatoryClaimRisk',
    'safetyClaimRisk',
    'discriminationClaimRisk',
  ],
};


// ── Auto-generated CommonJS exports (sync_foundation.mjs) ──
module.exports.WF4_GUARDRAILS = WF4_GUARDRAILS;
module.exports.buildReviewClassificationPrompt = buildReviewClassificationPrompt;
module.exports.buildReviewResponsePrompt = buildReviewResponsePrompt;
module.exports.buildReviewRequestPrompt = buildReviewRequestPrompt;
module.exports.buildDisputePrompt = buildDisputePrompt;
