/*
 * AUTOGENERATED FROM workflow_15_ai_brain.ts — DO NOT EDIT BY HAND
 * Source: ../maroa-ai-marketing-automator/src/lib/prompts/workflow_15_ai_brain.ts
 * Regenerate: node scripts/sync_foundation.mjs
 * --------------------------------------------------------------------------- 
 * Source SHA-256 (first 12): fbce312f492d
 */
'use strict';

/**
 * Workflow #15 — AI Brain (Conversational Command Center)
 * ============================================================================
 * The Chief of Staff. Not a chatbot — a persistent, learning, acting strategic
 * partner that synthesizes across all client data and executes via the other
 * 14 workflows.
 *
 * Per MAROA_15_WORKFLOWS_V2 section "WORKFLOW #15 — AI BRAIN".
 *
 * Architecture:
 *   - Multimodal input (text, voice, image, URL, file)
 *   - Three memory layers (short-term conversation, medium-term 30-90d,
 *     long-term vector-searchable via Pinecone)
 *   - Tool use transparency (show the work, explain reasoning)
 *   - Intelligent model routing (Haiku / Sonnet / Opus by query complexity)
 *   - Action execution via other workflows with approval gates
 *   - Proactive intelligence (morning check-in, urgent alerts, opportunity alerts)
 * ============================================================================
 */

const { buildSystemPrompt } = require('./foundation.js');

// ---------------------------------------------------------------------------
// Message + conversation types
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Tool registry — what Brain can DO (not just say)
// Each maps to a workflow or integration. Approval gates marked.
// ---------------------------------------------------------------------------

const BRAIN_TOOLS = {
  // Content (WF1)
  content_draft: { workflow: 'wf1', approval: true, description: 'Draft a social post via WF1 pipeline' },
  content_variants: { workflow: 'wf1', approval: true, description: 'Generate N variants of a concept' },
  content_schedule: { workflow: 'wf1', approval: true, description: 'Queue content for a specific time' },
  content_publish_now: { workflow: 'wf1', approval: true, description: 'Publish immediately' },
  // Ads (WF3)
  ads_pause: { workflow: 'wf3', approval: true, description: 'Pause a campaign' },
  ads_resume: { workflow: 'wf3', approval: true, description: 'Resume a paused campaign' },
  ads_reallocate: { workflow: 'wf3', approval: true, description: 'Shift budget between campaigns or channels' },
  ads_create: { workflow: 'wf3', approval: true, description: 'Scaffold a new campaign' },
  // Leads (WF2)
  leads_reclassify: { workflow: 'wf2', approval: false, description: 'Re-run scoring on a lead' },
  leads_set_priority: { workflow: 'wf2', approval: false, description: 'Flag a lead as high priority' },
  leads_assign: { workflow: 'wf2', approval: false, description: 'Route lead to a specific owner' },
  // Email (WF7)
  email_send_segment: { workflow: 'wf7', approval: true, description: 'Draft + schedule a segment email' },
  email_trigger_sequence: { workflow: 'wf7', approval: true, description: 'Enroll a contact in a lifecycle sequence' },
  // Reviews (WF4)
  reviews_draft_reply: { workflow: 'wf4', approval: true, description: 'Draft a response to a review' },
  reviews_request_review: { workflow: 'wf4', approval: false, description: 'Trigger a review request to a customer' },
  // Studio (WF10)
  studio_generate_reel: { workflow: 'wf10', approval: true, description: 'Generate a Reel via Segmind/Higgsfield' },
  studio_generate_image: { workflow: 'wf10', approval: true, description: 'Generate a hero image' },
  studio_generate_variants: { workflow: 'wf10', approval: true, description: 'Create variants of an existing asset' },
  // Analytics / synthesis
  report_generate_mini_brief: { workflow: 'wf13', approval: false, description: 'Generate a mini brief for a specific window' },
  report_compare_platforms: { workflow: 'wf13', approval: false, description: 'Cross-platform comparison' },
  report_export_pdf: { workflow: 'wf13', approval: false, description: 'Export a brief as PDF' },
  // Competitive / research
  research_competitor_analysis: { workflow: 'wf5', approval: false, description: 'Deep research on a competitor' },
  research_scrape_url: { workflow: 'wf5', approval: false, description: 'Scrape and analyze a URL' },
  research_customer_insights: { workflow: 'wf8', approval: false, description: 'Query customer voice data' },
  // Launch / budget (WF12, WF14)
  launch_plan: { workflow: 'wf12', approval: true, description: 'Build a launch plan' },
  budget_simulate: { workflow: 'wf14', approval: false, description: 'What-if budget simulation' },
  budget_reallocate: { workflow: 'wf14', approval: true, description: 'Reallocate budget across channels' },
  // CRM actions
  crm_update_record: { workflow: 'wf2', approval: false, description: 'Update a CRM record' },
  crm_schedule_followup: { workflow: 'wf2', approval: false, description: 'Schedule a follow-up task' },
  // Memory
  memory_recall: { workflow: 'wf15', approval: false, description: 'Recall from long-term memory (Pinecone)' },
  memory_store: { workflow: 'wf15', approval: false, description: 'Persist a fact or decision to memory' },
};

// ---------------------------------------------------------------------------
// Model routing — Haiku / Sonnet / Opus by query complexity
// ---------------------------------------------------------------------------

/**
 * Heuristic pre-routing (cheap). The backend uses this before invoking Brain
 * to save cost on simple factual queries. Brain can always upgrade mid-turn.
 *
 *   Haiku:  simple factual ("what's my follower count", "when was X posted")
 *   Sonnet: standard strategic ("write a caption", "draft an email")
 *   Opus:   complex synthesis ("analyze our competitive position",
 *           "should I raise prices", "why is CAC climbing")
 */
function routeModel(query, hasAttachments) {
  const q = query.toLowerCase().trim();
  const wordCount = q.split(/\s+/).length;

  // Attachments almost always warrant Sonnet minimum
  if (hasAttachments) return { model: 'sonnet', rationale: 'multimodal input requires vision' };

  // Opus triggers
  const opusSignals = [
    /why (is|are|did|has|have)/,
    /should (i|we)/,
    /what (would happen|if)/,
    /analy(ze|se|sis)/,
    /compar(e|ison|ing)/,
    /strateg(y|ic|ies)/,
    /recommend/,
    /diagnose/,
    /troubleshoot/,
    /predict/,
    /forecast/,
  ];
  if (opusSignals.some((r) => r.test(q))) {
    return { model: 'opus', rationale: 'strategic synthesis or deep reasoning requested' };
  }
  if (wordCount > 40) {
    return { model: 'opus', rationale: 'long compound query' };
  }

  // Sonnet triggers (execution-oriented)
  const sonnetSignals = [
    /write|draft|generate|create|make/,
    /caption|post|email|reel|ad/,
    /schedule|queue|pause|resume|launch/,
    /explain|describe|summari[sz]e/,
  ];
  if (sonnetSignals.some((r) => r.test(q))) {
    return { model: 'sonnet', rationale: 'content generation or action execution' };
  }

  // Haiku default for short factual
  if (wordCount <= 12) {
    return { model: 'haiku', rationale: 'simple factual query' };
  }

  return { model: 'sonnet', rationale: 'default for ambiguous medium query' };
}

const MODEL_COST_PER_100_MESSAGES = {
  haiku: 0.01,
  sonnet: 0.15,
  opus: 0.75,
};

// ---------------------------------------------------------------------------
// System prompt — the Chief of Staff persona
// ---------------------------------------------------------------------------

function buildBrainSystemPrompt(
  ctx,
  memory,
) {
  const addendum = `
WORKFLOW #15 — AI BRAIN, CONVERSATIONAL COMMAND CENTER

You are the Chief of Staff for ${ctx.businessName}. Not a chatbot. Not a
marketing assistant. The Chief of Staff — a persistent, learning, acting
strategic partner who synthesizes across every dataset and every workflow
and delivers answers the way a $500K/year senior executive team would.

You are accessible 24/7. You remember everything. You execute — you don't
just talk. You explain your reasoning like a senior strategist teaching a
junior so the owner grows alongside you.

OPERATING PRINCIPLES

1. ANSWER, THEN ACT
   The owner asks a question → answer it briefly, then surface the concrete
   actions you can take. Never make them navigate dashboards.

2. SHOW THE WORK
   When you use tools, narrate in real-time: "Pulling your Meta Ads data…",
   "Checking Google Analytics…". Users seeing progress trust autonomy.
   After every action, a crisp recap: what you did, why, and what's next.

3. EXPLAIN WHEN ASKED
   If the owner asks "why did you do that?", respond like a senior strategist
   teaching a junior: the decision, the evidence, the alternatives you
   considered, the next step. Build their strategic intuition over time.

4. RESPECT APPROVAL GATES
   Actions marked \`approval: true\` in BRAIN_TOOLS MUST request approval
   before executing. Draft, prepare, stage — but do not ship until the owner
   confirms. Draft the approval request crisply: here's what I'll do, why,
   and the risk/reward. One tap to approve.

5. MATCH THE LANGUAGE AND TONE
   Auto-detect the owner's input language. Respond in kind. Honor the brand
   voice defined in BRAND CONTEXT. Albanian, Spanish, German — first-class
   native, not translated.

6. PRIORITIZE RUTHLESSLY
   Out of 50 things you could surface, pick the 3 that matter. The owner is
   a busy operator, not an analyst.

7. CITE FRAMEWORKS WHEN LOAD-BEARING
   When your recommendation rests on Cialdini, StoryBrand, Kahneman, JTBD,
   or an industry playbook principle, NAME it. "I'm recommending this
   because of loss aversion — 2.5x sensitivity on losses vs gains — and
   your churn signal is a loss framing opportunity."

8. PROACTIVE WHEN APPROPRIATE
   Morning check-ins (if enabled): the 3 things worth knowing.
   Urgent alerts: policy reviews, budget overrides, competitor moves.
   Opportunity alerts: trending topics, pattern breaks, timing windows.
   Celebration moments: milestones. Don't be spammy — be the Chief of Staff.

9. NEVER A BLACK BOX
   Every action comes with a rationale. Every recommendation traces back to
   data. If confidence is low, say so explicitly: "I'm not sure — here's
   what I'd need to answer properly."

10. LEARN THIS OWNER
    Calibrate over time. If verbose responses get rejected, be terse. If
    the owner always drills into SEO, expand that. If they always reject
    "scale ads" recommendations, shift toward organic. The flywheel is:
    use → learn → personalize → trust → delegate → use.

MEMORY LAYERS (use them)

Short-term: the last 50 messages of THIS conversation — reference freely.
Medium-term (last 30–90 days): recent decisions + outcomes + active
  strategies. Use when the owner asks about "last month" or "recently".
Long-term: Pinecone vector memory per-client. Use \`memory_recall\` tool
  when the owner references past decisions, documents, or onboarding data.

TOOL USE PROTOCOL

When you decide to act, emit a tool call with:
  { tool, inputSummary, rationale, alternativesConsidered, requiresApproval }
The backend will execute (or pause for approval if \`requiresApproval\`).
Never fabricate tool results. Wait for actual return values.

RESPONSE SHAPE

Most responses should be:
  - 1–3 sentence direct answer to what was asked
  - (if action needed) clearly marked action request with approval button
  - (if explaining) senior-strategist-teaching-junior mode when requested

Never pad. Never use "I'd be happy to help!" or other chatbot filler.

MEMORY SNAPSHOT (injected per turn)
${renderMemorySnapshot(memory)}
`.trim();

  return buildSystemPrompt(ctx, addendum);
}

// ---------------------------------------------------------------------------
// Memory snapshot — what Brain has loaded for this turn
// ---------------------------------------------------------------------------

function renderMemorySnapshot(m) {
  const lines = [];
  if (m.recentDecisions.length) {
    lines.push('Recent decisions:');
    for (const d of m.recentDecisions.slice(0, 8)) {
      lines.push(`  ${d.date}: ${d.decision}${d.outcome ? ` → ${d.outcome}` : ''}`);
    }
  }
  if (m.activeStrategies.length) {
    lines.push('Active strategies:');
    for (const s of m.activeStrategies.slice(0, 6)) {
      lines.push(`  ${s.name} [${s.status}] — ${s.state}`);
    }
  }
  if (m.recentLearnings.length) {
    lines.push('Recent learnings (from WF1 learning loop):');
    for (const l of m.recentLearnings.slice(0, 5)) {
      lines.push(`  ${l.pattern} → ${(l.lift * 100).toFixed(0)}% lift (n=${l.sampleSize})`);
    }
  }
  lines.push('Owner preferences:');
  lines.push(`  verbosity=${m.ownerPreferences.verbosity}, depth=${m.ownerPreferences.technicalDepth}, language=${m.ownerPreferences.language}`);
  if (m.ownerPreferences.topicsOfHighInterest.length)
    lines.push(`  high interest: ${m.ownerPreferences.topicsOfHighInterest.join(', ')}`);
  if (m.ownerPreferences.recommendationsOftenRejected.length)
    lines.push(`  often rejects: ${m.ownerPreferences.recommendationsOftenRejected.join(', ')} — shift away`);
  if (m.ownerPreferences.recommendationsOftenApproved.length)
    lines.push(`  often approves: ${m.ownerPreferences.recommendationsOftenApproved.join(', ')} — surface more`);
  if (m.longTermSummary) {
    lines.push('Long-term summary:');
    lines.push(`  ${m.longTermSummary}`);
  }
  if (m.lastBriefId) lines.push(`Last weekly brief id: ${m.lastBriefId}`);
  if (m.activeApprovalCount != null) lines.push(`Pending approvals right now: ${m.activeApprovalCount}`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Proactive prompts — morning check-in, urgent alert, opportunity alert
// ---------------------------------------------------------------------------

function buildMorningCheckInPrompt(ctx, memory) {
  const system = buildBrainSystemPrompt(ctx, memory);
  const user = `
Generate the morning check-in for ${ctx.businessName}.

Requirements:
- 3 items maximum. Pick the 3 that matter most from the last 24h.
- Each item: 1 sentence of fact + 1 sentence of meaning.
- End with an open question: "Reply with any questions or tell me what to prioritize."
- Tone: warm, direct, trusted advisor. No chatbot filler.
- Language: ${ctx.primaryLanguages[0] ?? 'en'}.
- If there's nothing material to report, say so honestly and suggest a focus for the day.
`.trim();
  return { system, user };
}

function buildUrgentAlertPrompt(
  ctx,
  memory,
  alert,
) {
  const system = buildBrainSystemPrompt(ctx, memory);
  const user = `
Urgent alert detected: ${alert.kind} (severity: ${alert.severity}).
Summary: ${alert.summary}
Data: ${JSON.stringify(alert.data)}

Generate the alert to the owner. Must include:
1. The fact in one sentence.
2. What you (Brain) have already done (auto-mitigation if applicable).
3. What needs the owner's decision now, with 2–3 options presented clearly.
4. Deadline — how long do they have before the situation gets worse?

Tone: calm, professional. Never alarmist. Never dismissive. This is a fire
you've controlled but the owner needs to know.
`.trim();
  return { system, user };
}

// ---------------------------------------------------------------------------
// Guardrails
// ---------------------------------------------------------------------------

const WF15_GUARDRAILS = {
  maxContextMessages: 50,
  monthlyMessageCap: {
    growth: 500,
    agency: null, // unlimited fair-use
    enterprise: null,
  },
  autoEscalateToOpusWordCount: 40,
  sensitiveDataMasking: {
    creditCardsRegex: /\b\d{4}[- ]?\d{4}[- ]?\d{4}[- ]?\d{4}\b/g,
    ssnRegex: /\b\d{3}-\d{2}-\d{4}\b/g,
  },
  cannotExecuteWithoutApproval: [
    'ads_pause',
    'ads_resume',
    'ads_reallocate',
    'ads_create',
    'content_publish_now',
    'content_schedule',
    'email_send_segment',
    'studio_generate_reel',
    'studio_generate_image',
    'budget_reallocate',
    'launch_plan',
  ],
  proactive: {
    morningCheckInHourLocal: 7, // owner can disable
    minHoursBetweenProactiveMessages: 4,
    urgentAlertOverrideQuietHours: true,
  },
};


// ── Auto-generated CommonJS exports (sync_foundation.mjs) ──
module.exports.BRAIN_TOOLS = BRAIN_TOOLS;
module.exports.MODEL_COST_PER_100_MESSAGES = MODEL_COST_PER_100_MESSAGES;
module.exports.WF15_GUARDRAILS = WF15_GUARDRAILS;
module.exports.routeModel = routeModel;
module.exports.buildBrainSystemPrompt = buildBrainSystemPrompt;
module.exports.buildMorningCheckInPrompt = buildMorningCheckInPrompt;
module.exports.buildUrgentAlertPrompt = buildUrgentAlertPrompt;
